services:
  nodo1:
    image: mongo
    ports:
      - 30001:27017
    volumes:
      - $HOME/mongoclusterdata/nodo1:/data/db
    networks:
      - mongocluster
    command: mongod --replSet usuarios
  nodo2:
    image: mongo
    ports:
      - 30002:27017
    volumes:
      - $HOME/mongoclusterdata/nodo2:/data/db
    networks:
      - mongocluster
    command: mongod --replSet usuarios
    depends_on :
      - nodo1
  nodo3:
    image: mongo
    ports:
      - 30003:27017
    volumes:
      - $HOME/mongoclusterdata/nodo3:/data/db
    networks:
      - mongocluster
    command: mongod --replSet usuarios
    depends_on :
        - nodo2

networks:
  mongocluster:
    driver: bridge